stages:
  - build
  - test

build_frontend:
  stage: build
  script:
    - cd frontend
    - npm install
    - npm run build
    
build_server:
  stage: build
  script:
    - cd server
    - npm install
    - npm run build

test_frontend:
  stage: test
  script:
    - cd frontend
    - npm install
    - npm run test

test_server:
  stage: test
  script:
    - cd server
    - npm install
    - npm run test