export const FETCH_COMPANIES = 'FETCH_COMPANIES';
export type FETCH_COMPANIES = typeof FETCH_COMPANIES;

export const FETCH_COMPANIES_REJECTED = 'FETCH_COMPANIES_REJECTED';
export type FETCH_COMPANIES_REJECTED = typeof FETCH_COMPANIES_REJECTED;

export const FETCH_COMPANIES_FULLFILLED = 'FETCH_COMPANIES_FULFILLED';
export type FETCH_COMPANIES_FULLFILLED = typeof FETCH_COMPANIES_FULLFILLED;
